# Generated by Django 4.1 on 2022-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="admin", name="role",),
        migrations.RemoveField(model_name="content_owner", name="role",),
        migrations.RemoveField(model_name="customer", name="role",),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
