# Generated by Django 4.1 on 2022-08-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pixel", "0002_remove_admin_role_remove_content_owner_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="user_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="content_owner",
            name="user_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="customer",
            name="user_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
