# Generated by Django 4.0.6 on 2022-08-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixel', '0003_admin_user_name_content_owner_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isSelected',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
